name: Image Scan
on:
  push:
    branches: [ "main" ]
  pull_request:
jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write # Required to upload SARIF results to the Security tab
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build an image from Dockerfile
      run: docker build -t wikitable2json:latest .

    - name: Run Trivy vulnerability scan
      uses: aquasecurity/trivy-action@v0.33.1
      with:
        image-ref: 'wikitable2json:latest'
        ignore-unfixed: true
        output: 'trivy-results.sarif'
        severity: 'CRITICAL,HIGH' # Fail build on Critical or High vulnerabilities
        exit-code: '1'
        format: sarif
        limit-severities-for-sarif: true
        vuln-type: os,library
        scanners: vuln

    - name: Upload Trivy results to GitHub Security
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: trivy-results.sarif
